language: java
sudo: required
dist: trusty
jdk: oraclejdk9
services:
- docker
env:
  global:
  - REGISTRY_USER=travisinnov
  - secure: yPo+t6cJpZLiFhMB6UfpELDFmtICNBjP34dsSNJg49440QSTeYt96KfBzbHVjdBkTQXWWORbIoVcZW1ypj6JkwbDNlaKXaK/l/OHh3iDeVCPgyLdFd6aFUUwdBFon4zKpMxxLkAw5xaITQ61nbO1nrk+8mXGBVNHuDRI43dakCZdxk/rmBiMjrRIeYzift1+qQezp86I4xRDPnV5eJYWmCGqfT0DCibyeSUZw6XZ5me4ZqPeq6OeGiObkibD5O8ifm5T0hFr8mqjKIe+36bYNJOfii7OJ68cle9xDOchmOGkuGF3naZho28AdMXGDMAdEadkrK9weRqRj+yKPl41G0XnxTqY9zGvvQLfd/q5OxNM2zT0ylmhwuCMsIzl7aIMvfLg6IrVogbvqWv+CXBxOlgBR5Rqj3w42WUJbHzJeAK/9bl1yDuTFH83fQl56LBVH3CCWr4XRUidYhw/58jI6CPxnQXlKTlckSzvvqHhZ9zpM5AmnCT/PK1GjJInHWPLIKz1xSTccBRbn0nLzKyyJrFl8m9IOtomdWlQnzLrQoE3E1Uof3n+i55Ezv8xw4lwpNe5x0qrrvZ11PIn9+a84d/z+TCUGJRCWbteKFCCA5lC5Mgggyi/QmNF3ELNgL9DwLTIGxQAsDqJkZHAgbGW7OB8+jFzxUG7qA30gDy70Tg=
before_script:
- docker pull yfalco/pns-innov-back || true
script:
- "./mvnw clean install -B"
- docker build --pull --cache-from yfalco/pns-innov-back --tag yfalco/pns-innov-back
  .
- docker images
before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push yfalco/pns-innov-back
before_install:
- chmod +x mvnw
