language: java
sudo: true
dist: trusty
jdk: oraclejdk9
services:
- docker
env:
  global:
  - REGISTRY_USER=travisinnov
  - secure: YqgJjbLXw12PB5WtFq1RLAB0g7Y2tPKDzkyDAtlq4HIen1MeCNE5ua+7y5un9b59Draqzxe2Azsd4oTNEJMFUhtAcz8eehSrY9Hr5aT1VGFLU6HgievggZqxEkSZcVStYvjvDYFA3cCB5J/wmM9mavNwbf/595wt95L44Lvt3DZLFxu+93VaX2xjxOlrgh7Q1JKMOZHlFK4mg2jKHkbR7pwYzGC+0k6AcXAknOuyza2TyrU9oJype3V9kYXjyPSiZEYYW8x2kyX8vqJJ25SvNLKHae4csphfklhMR1vFCxwN5s+4EQY4uX5zqETQ/1Lg+dNkwQrXzW7K697Q2bm/IeP7qflBcw7UupqwzWduD6Ha0wniJ6Hoie8/QZteJw/mnYXXeO9yDMjDNwp4zTzeaYx1LFyGeU9Kk9y7dU0Ym/617boLCjRCZrVSKNrFh5YFBhlXWpxPMgCtPGXFqXwA7utzdOKIm2LTxkkvWOr6EIx8+ikO1p8LzH7OabMOkjVIod7N3fR1A8CMwV6yW5NmnkBz2b9tWTaFHmsFHs4+CvUWkMTTwNPEzooB/Dak3KbhnjV4Mz1qAbpjz0DRgNlyiCqScIn8Fvosb01IB85WjqMggDPUcj6e9k67IdmaPT4G63E5FAY5UpUrXz6cQF2UqZgXVm5xiXajTzR6ipM7gJU=
before_script:
- docker pull yfalco/pns-innov-back || true
script:
- "./mvnw clean install -B"
- docker build --pull --cache-from yfalco/pns-innov-back --tag yfalco/pns-innov-back
  .
- docker images
before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push yfalco/pns-innov-back
before_install:
- chmod +x mvnw
